develop:
    stage: development
    hostname: 3.234.180.107
    deploy_path: /var/www/html/zoom-industry

production:
    stage: production
    hostname: 3.234.180.107
    deploy_path: /var/www/html/zoom-industry
